#!/usr/bin/perl

$base  = '/home/adawson/Documents';
$rhost = '66.57.25.212';
$rbase = '/home/adawson';

@modules = ("school", "personal");

print "\nsync: use ctrl+c to abort at any time...\n\n";
print "possible directories:\n";

print "  ", join(', ', @modules);

print "\n\ndirectory? ";
chomp($directory = <>);

print "put or get? ";
chomp($direction = <>);

print "destructive (y/n)? ";
chomp($destructive = <>);

print "dry run (y/n)? ";
chomp($dry_run = <>);

if (! -d "$base/$directory") {
  die "No such directory: $directory.\n";
}

@cmd = ('rsync', '-avuz');

push(@cmd, '-n') if $dry_run =~ /y/i;
push(@cmd, '--delete-after') if $destructive =~ /y/i;

if ($direction =~ /get/i) {
	push(@cmd, "$rhost:$rbase/$directory");
	push(@cmd, "$base");
}

if ($direction =~ /put/i) {
	push(@cmd, "$base/$directory");
	push(@cmd, "$rhost:$rbase");
}

exec(@cmd);
